### ISSUE TITLE
Decreasing kafka lag by skipping old full refreshes

### ISSUE THREAD

**Issue by slemrmartin** [RedHatInsights/topological_inventory-persister#66]
Because we have only full-refreshes now, persister needs to process lots of data. 

It's probable, if there is a big kafka lag, that we are processing older refresh than it's available. So we can skip them after some time (let's say 60 minutes old)

---

- [x] https://github.com/RedHatInsights/topological_inventory-persister/pull/65
- [x] https://github.com/RedHatInsights/topological_inventory-ingress_api/pull/94
- [x] https://github.com/RedHatInsights/topological_inventory-ingress_api-client-ruby/pull/68
- [x] https://github.com/RedHatInsights/topological_inventory-providers-common/pull/45
- [x] https://github.com/RedHatInsights/topological_inventory-amazon/pull/71
- [x] https://github.com/RedHatInsights/topological_inventory-ansible_tower/pull/117
- [x] https://github.com/RedHatInsights/topological_inventory-azure/pull/36
- [x] https://github.com/RedHatInsights/topological_inventory-openshift/pull/131

**Comment by slemrmartin** [comment]
@syncrou @lindgrenj6 top-level issue for cross-repo feature

**Comment by syncrou** [comment]
All referenced PRs are merged.  Closing
